name: Marketplace and Reusable workflows
run-name: "${{ github.actor }}'s Marketplace and Reuse Workflow Run"

on:
  workflow_dispatch

jobs:
  setup-python-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # You can change this to any version you need

      - name: Show Python version
        run: python --version
