name: Multi-Trigger Example
run-name: "${{ github.actor }}'s Example2 Workflow Run"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
#  schedule:
#    - cron: '*/2 * * * *'  # Runs every Monday at 09:00 UTC

jobs:
  show-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger
        run: "echo 'Triggered by: ${{ github.event_name }}'"
