
name: Multi-Trigger Example
run-name: "${{ github.actor }}'s Example2 Workflow Run"
# Define multiple trigger types
on:
  push:
    branches: [main]
# Trigger on push to main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'
jobs:
  show-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger
        run: "echo 'Triggered by: ${{ github.event_name }}*"
