name: Multi-Trigger Example
run-name: "${{ github.actor }}'s Example2 Workflow Run"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9:00 AM UTC

jobs:
  show-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger
        run: echo "Triggered by: ${{ github.event_name }}"
